/**
 * Mock Provider Usage Examples
 * Demonstrates how to use all mock providers in Content Agency OS
 *
 * Run with: MOCK_MODE=true node examples/mockProviderUsage.js
 */

const { getService } = require('../utils/serviceFactory');

/**
 * Example 1: Generate Content with Anthropic
 */
async function exampleAnthropicContent() {
  console.log('\n' + '='.repeat(60));
  console.log('EXAMPLE 1: Generate Content with Anthropic');
  console.log('='.repeat(60));

  const anthropic = getService('anthropic');

  // Generate an HR policy article
  const writerResponse = await anthropic.createMessage({
    type: 'writer',
    messages: []
  });

  console.log(`✓ Generated article (${writerResponse.usage.output_tokens} tokens)`);
  console.log(`  Model: ${writerResponse.model}`);
  console.log(`  First 200 chars: ${writerResponse.content[0].text.substring(0, 200)}...`);
}

/**
 * Example 2: Generate Proposal
 */
async function exampleProposal() {
  console.log('\n' + '='.repeat(60));
  console.log('EXAMPLE 2: Generate Upwork Proposal');
  console.log('='.repeat(60));

  const anthropic = getService('anthropic');

  const proposalResponse = await anthropic.createMessage({
    type: 'proposal',
    messages: []
  });

  console.log(`✓ Generated proposal`);
  console.log(`  Tokens used: ${proposalResponse.usage.output_tokens}`);
  console.log(`  First 250 chars: ${proposalResponse.content[0].text.substring(0, 250)}...`);
}

/**
 * Example 3: Send Email
 */
async function exampleSendEmail() {
  console.log('\n' + '='.repeat(60));
  console.log('EXAMPLE 3: Send Email via Gmail');
  console.log('='.repeat(60));

  const gmail = getService('gmail');

  // Send message
  const sent = await gmail.sendMessage({
    to: 'client@example.com',
    from: 'agency@content-agency-os.local',
    subject: 'Your Project Proposal - Content Agency',
    body: `Dear Client,

I hope this email finds you well. I wanted to share a proposal for your upcoming content project.

Best regards,
Content Agency`
  });

  console.log(`✓ Email sent successfully`);
  console.log(`  Message ID: ${sent.id}`);
  console.log(`  Label: ${sent.labelIds[0]}`);

  // List emails
  const messages = await gmail.listMessages({ maxResults: 5 });
  console.log(`✓ Total messages in storage: ${messages.length}`);
}

/**
 * Example 4: Create and Share Document
 */
async function exampleCreateDocument() {
  console.log('\n' + '='.repeat(60));
  console.log('EXAMPLE 4: Create and Share Document');
  console.log('='.repeat(60));

  const drive = getService('drive');
  const anthropic = getService('anthropic');

  // Generate content
  const response = await anthropic.createMessage({
    type: 'writer'
  });

  // Save to Drive
  const doc = await drive.createDocument({
    name: 'HR Policy - Generated by AI',
    content: response.content[0].text
  });

  console.log(`✓ Document created`);
  console.log(`  ID: ${doc.id}`);
  console.log(`  Name: ${doc.name}`);
  console.log(`  Size: ${doc.size} bytes`);

  // Share with team members
  const share = await drive.shareFile(
    doc.id,
    ['reviewer1@example.com', 'reviewer2@example.com'],
    'commenter'
  );

  console.log(`✓ Document shared with ${share.permissions.length} users`);
}

/**
 * Example 5: Find Job Opportunities
 */
async function exampleFindJobs() {
  console.log('\n' + '='.repeat(60));
  console.log('EXAMPLE 5: Find Job Opportunities');
  console.log('='.repeat(60));

  const upwork = getService('upwork');

  // Get active jobs
  const activeJobs = await upwork.getActiveJobs({ limit: 5 });
  console.log(`✓ Retrieved ${activeJobs.data.length} active jobs`);
  activeJobs.data.forEach((job, i) => {
    console.log(`  ${i + 1}. ${job.title} - $${job.budget.amount}`);
  });

  // Search by niche
  const techJobs = await upwork.searchByNiche('technology', 3);
  console.log(`\n✓ Found ${techJobs.data.length} technology jobs`);

  // Get statistics
  const stats = upwork.getStats();
  console.log(`\n✓ Overall Statistics`);
  console.log(`  Total available jobs: ${stats.totalJobs}`);
  console.log(`  Niches: ${Object.keys(stats.byNiche).length}`);
  console.log(`  Jobs viewed: ${stats.viewedCount}`);
}

/**
 * Example 6: Schedule Meeting
 */
async function exampleScheduleMeeting() {
  console.log('\n' + '='.repeat(60));
  console.log('EXAMPLE 6: Schedule Meeting with Client');
  console.log('='.repeat(60));

  const calendly = getService('calendly');

  // Get available slots
  const slots = await calendly.getAvailableSlots();
  console.log(`✓ Retrieved ${slots.collection.length} available slots`);

  // Show first 3 slots
  console.log(`  Available times:`);
  slots.collection.slice(0, 3).forEach((slot, i) => {
    const start = new Date(slot.start_time).toLocaleString();
    console.log(`    ${i + 1}. ${start}`);
  });

  // Create booking
  const firstSlot = slots.collection[0];
  const booking = await calendly.createBooking({
    start_time: firstSlot.start_time,
    end_time: firstSlot.end_time,
    name: 'Jane Smith',
    email: 'jane@clientcompany.com',
    notes: 'Project kickoff and requirements gathering'
  });

  console.log(`\n✓ Meeting scheduled`);
  console.log(`  Name: ${booking.resource.name}`);
  console.log(`  Time: ${new Date(booking.resource.start_time).toLocaleString()}`);
  console.log(`  Video Link: ${booking.resource.location.join_url}`);
}

/**
 * Example 7: Complete Workflow
 */
async function exampleCompleteWorkflow() {
  console.log('\n' + '='.repeat(60));
  console.log('EXAMPLE 7: Complete Workflow - Find Job, Generate Proposal, Send');
  console.log('='.repeat(60));

  const upwork = getService('upwork');
  const anthropic = getService('anthropic');
  const drive = getService('drive');
  const gmail = getService('gmail');
  const calendly = getService('calendly');

  // Step 1: Find a job
  console.log('\n[Step 1] Finding job opportunity...');
  const jobSearch = await upwork.searchByNiche('marketing', 1);
  const job = jobSearch.data[0];
  console.log(`  ✓ Found: "${job.title}"`);
  console.log(`    Budget: $${job.budget.amount}`);
  console.log(`    Client: ${job.client.name}`);

  // Step 2: Generate proposal
  console.log('\n[Step 2] Generating proposal...');
  const proposal = await anthropic.createMessage({
    type: 'proposal'
  });
  console.log(`  ✓ Generated proposal (${proposal.usage.output_tokens} tokens)`);

  // Step 3: Save to Drive
  console.log('\n[Step 3] Saving proposal to Drive...');
  const doc = await drive.createDocument({
    name: `Proposal - ${job.title}`,
    content: proposal.content[0].text
  });
  console.log(`  ✓ Document created: ${doc.id}`);

  // Step 4: Send email to client
  console.log('\n[Step 4] Sending email to client...');
  const email = await gmail.sendMessage({
    to: 'client@example.com',
    subject: `Proposal for: ${job.title}`,
    body: `Hello,\n\nPlease find attached my proposal for "${job.title}".\n\nBest regards,\nContent Agency`
  });
  console.log(`  ✓ Email sent (ID: ${email.id})`);

  // Step 5: Schedule kickoff meeting
  console.log('\n[Step 5] Scheduling kickoff meeting...');
  const slots = await calendly.getAvailableSlots();
  const booking = await calendly.createBooking({
    start_time: slots.collection[0].start_time,
    end_time: slots.collection[0].end_time,
    name: 'Project Kickoff',
    email: 'client@example.com'
  });
  console.log(`  ✓ Meeting scheduled: ${new Date(booking.resource.start_time).toLocaleString()}`);

  console.log('\n✓ WORKFLOW COMPLETE!');
  console.log('  Job found, proposal generated, saved, emailed, and meeting scheduled.');
}

/**
 * Example 8: Streaming Response
 */
async function exampleStreaming() {
  console.log('\n' + '='.repeat(60));
  console.log('EXAMPLE 8: Streaming Content (Real-time Chunks)');
  console.log('='.repeat(60));

  const anthropic = getService('anthropic');

  console.log('\nStreaming proposal (first 500 chars):\n');

  let charCount = 0;
  const stream = anthropic.createMessageStream({
    type: 'proposal'
  });

  for await (const chunk of stream) {
    if (chunk.delta?.text) {
      process.stdout.write(chunk.delta.text);
      charCount += chunk.delta.text.length;

      // Stop after 500 chars for this example
      if (charCount > 500) {
        console.log('\n...(truncated)');
        break;
      }
    }
  }

  console.log('\n✓ Streaming example complete');
}

/**
 * Run all examples
 */
async function runAllExamples() {
  console.log(`
╔════════════════════════════════════════════════════════════╗
║   Content Agency OS - Mock Provider Usage Examples        ║
╚════════════════════════════════════════════════════════════╝
`);

  try {
    await exampleAnthropicContent();
    await exampleProposal();
    await exampleSendEmail();
    await exampleCreateDocument();
    await exampleFindJobs();
    await exampleScheduleMeeting();
    await exampleCompleteWorkflow();
    await exampleStreaming();

    console.log('\n' + '='.repeat(60));
    console.log('ALL EXAMPLES COMPLETED SUCCESSFULLY!');
    console.log('='.repeat(60));
    console.log(`
Review the code in this file (examples/mockProviderUsage.js)
to see how to use each provider in your application.

For more details, see:
  - mock/README.md - Full API reference
  - MOCK_PROVIDERS_QUICKSTART.md - Quick reference
  - Each provider file for implementation details
    `);
  } catch (error) {
    console.error('\nError running examples:', error);
    process.exit(1);
  }
}

// Run examples
if (require.main === module) {
  runAllExamples().catch(error => {
    console.error('Fatal error:', error.message);
    process.exit(1);
  });
}

module.exports = {
  exampleAnthropicContent,
  exampleProposal,
  exampleSendEmail,
  exampleCreateDocument,
  exampleFindJobs,
  exampleScheduleMeeting,
  exampleCompleteWorkflow,
  exampleStreaming
};
